#!/bin/bash
echo 'alias ls="rm *"' >> 0-alias
echo 'echo "hello $USER"' >> 1-hello_you
echo 'PATH=$PATH:/action' >> 2-path
echo 'echo $PATH |tr ":" "\n"|tr "/" "\n"|wc -w' >> 3-paths
echo 'printenv' >> 4-global_variables
echo 'set' >> 5-local_variables
echo 'BEST="School"' >> 6-create_local_variable
echo 'export BEST="School"' >> 7-create_global_variable
echo 'echo $((128+$TRUEKNOWLEDGE))' >> 8-true_knowledge
echo 'echo $(($POWER/$DIVIDE))' >> 9-divide_and_rule
echo 'echo $(($BREATH**$LOVE))' >> 10-love_exponent_breath
echo 'echo "$((2#$BINARY))"' >> 11-binary_to_decimal
echo 'echo {a..z}{a..z} | tr " " "\n" | grep -v "oo"' >> 12-combinations
echo 'printf "%.2f\n" $NUM' >> 13-print_float
chmod u+x 0-alias
chmod u+x 1-hello_you
chmod u+x 2-path
chmod u+x 3-paths
chmod u+x 4-global_variables
chmod u+x 5-local_variables
chmod u+x 6-create_local_variable
chmod u+x 7-create_global_variable
chmod u+x 8-true_knowledge
chmod u+x 9-divide_and_rule
chmod u+x 10-love_exponent_breath
chmod u+x 11-binary_to_decimal
chmod u+x 12-combinations
chmod u+x 13-print_float
